### ISSUE TITLE
[Question] How to load Full roassal + Roassal-UML-Calypso package ?

### ISSUE THREAD

**Issue by labordep** [pharo-graphics/Roassal#13]
Hi @akevalion, do you know how to load into my baseline **roassal full** + **Roassal-UML-Calypso** package ?
Why this package is not loaded with the full version ? Is it deprecated ?

Thanks for your help :)

**Comment by akevalion** [comment]
Hi, this package was requested by some users to be removed from core packages.
But yes you are right it can be in roassal full. I will added to full group

**Comment by labordep** [comment]
Ok thanks @akevalion :)
