### ISSUE TITLE
Visual glitch in example29Tick

### ISSUE THREAD

**Issue by tinchodias** [pharo-graphics/Roassal#15]
There is a tail here, that disappears when enabling "Show Dirty Rectangle":

<img width="722" alt="Screenshot 2023-10-29 at 10 13 05" src="https://github.com/pharo-graphics/Roassal/assets/3044265/a092b6fe-3c33-4b98-aea0-15e9e89fe332">

**Comment by JanBliznicenko** [comment]
There are actually many examples in `RSAnimationExamples` with similar issues (partially refreshing, not refreshing at all, do not displaying part of the content etc.):
* `example3Atom`
* `example20CircleWaves`
* `example21Lines`
* `example22Lines`
* `example23PerlnNoise`
* `example26Bezier`
* `example29Tick`
* `example31RoundRectangles`
* `example36Title`
* `example39Duna`

And in `RSSVGAnimationExamples`
* `example06AnimatedSVG`

**Comment by akevalion** [comment]
Hi, thank you very much for your feedback I fixed all examples.
For `example39Duna` I did not find any problem
<img width="986" alt="image" src="https://github.com/pharo-graphics/Roassal/assets/10532890/9e613f40-592e-40a4-81b7-e20a68b4bbb5">

**Comment by JanBliznicenko** [comment]
Ah, the problem with `example39Duna` is that the `RSExamplesBrowser` default size is way too small for it, so you have to wait a long time to the visible part to react the tiny cutout :)

![obrazek](https://github.com/pharo-graphics/Roassal/assets/9571633/a1e53429-ad99-4ef6-ab15-63ae60a12cb7)
