### ISSUE TITLE
Cleanup: Usage of "notNil" in Roassal

### ISSUE THREAD

**Issue by astares** [pharo-graphics/Roassal#19]
We have 47 senders of #notNil in Roassal - they should be changed to use #isNotNil as we want to deprecate #notNil later

```Smalltalk
(SystemNavigation default allSendersOf: #notNil)
	select: [:each | each package name beginsWith: 'Roassal-' ]
```

@akevalion can we clean them?

![image](https://github.com/pharo-graphics/Roassal/assets/5980033/4a5ff4af-e172-4cf9-841d-fcd3566a5da4)

**Comment by akevalion** [comment]
I have removed notNil from Roassal, it will be present in pharo version in a new release

**Comment by astares** [comment]
@akevalion Great - thanks!
