### ISSUE TITLE
You cannot remove shapes from a composite if it is not installed in a canvas.

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-graphics/Roassal#3]
If you try to remove a shape from a composite while it does not have aassigned shape index, it fails.

```smalltalk
com := RSComposite new.
s := RSBox new.
com addBasicShape: s.
com removeShape: s
```

I encountered this issue in some label tests we have.

**Comment by akevalion** [comment]
Hi, I can not reproduce the error in the last version of roassal
