### ISSUE TITLE
RSComposite>>#resetChildren does not reset shapeCollection

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-graphics/Roassal#7]
In `RSComposite>>#resetChildren`, the children are reset; however, the new `shapeCollection` stays untouched. This means the old shapes added to the composite are still stored and thus potentially displayed twice (see `visibleChildren` computation in `RSAthensRenderer>>#visitChildrenIfNecessary:`).

**Comment by akevalion** [comment]
done!
