### ISSUE TITLE
Unable to load, RSBoundingBox depends on non-existing trait RSTNode

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-graphics/Roassal#8]
RSBoundingBox depends on trait RSTNode that does not exist.

The trait usage was added in https://github.com/pharo-graphics/Roassal/commit/4cde8f4c5313c5d0978fa8fe6faa1fa525dfdc19#diff-3f7d1c3e38203d789fd80f0cd257599502122f3ce3798453f7c63dd4e0af6926

![error](https://github.com/pharo-graphics/Roassal/assets/9571633/163ba271-4f93-44f1-b0da-e41c304cb3c0)

**Comment by tinchodias** [comment]
Hello @JanBliznicenko it's here: https://github.com/pharo-graphics/RTree
Dependency needed in baseline

**Comment by akevalion** [comment]
Hi in order to load it depends
In pharo 12 Just push the button `Library>> Roassal >> Load.. >> Load full version`

in pharo 11, 10, 9

```st
#(Roassal3 Numeric) do: [:string |
  regExp := '*', string ,'*'.
  packages := RPackageOrganizer default packages
	  select: [ :each | regExp match: each name ].
  packages do: [ :each | each removeFromSystem ].
].

Metacello new
    baseline: 'Roassal';
    repository: 'github://pharo-graphics/Roassal';
    load.
```

**Comment by JanBliznicenko** [comment]
The problem was actually caused by my baseline black magic that overcomes https://github.com/pharo-project/pharo/issues/9913
I have reworked my baselines and RTree now loads properly. Thank you for pointing me out to the solution.
