### ISSUE TITLE
Duplicated baseline dependencies

### ISSUE THREAD

**Issue by JanBliznicenko** [pharo-graphics/Roassal#9]
In `BaselineOfRoassal>>#geometry:`, there are multiple external dependencies that are also present elsewhere. 

Dependency on `RoassalLayouts` in `layouts:` and `geometry:`.
Dependency on `RTree` in `rtree:` and `geometry:`.
Dependency on `NumericScales` in `numeric:` and `geometry:`.
Dependency on `OSSubprocess` in `subProcess:` and `geometry:`.
Dependency on `AIDatasets` in `aiDatasets:`, geometry **and also `dataFrame:`**.

`DataFrame` is only in `geometry:` because `dataFrame:` method mistakenly contains `AIDatasets` dependency.

It does not seem to cause any immediate issues, might just be redundant.

**Comment by akevalion** [comment]
Fixed
